//I used chatgpt to generate random data generated
export const dataset = [
  {
    car: {
      make: "Toyota",
      model: "Camry",
      year: "2020",
      serialPrice: 25000,
    },
    seller: {
      fullName: "John Doe",
      address: "Springfield, IL",
      contact: "555-123-4567",
    },
    sellingPrice: 23000,
    mileage: 15000,
    description: "Well-maintained sedan with excellent fuel efficiency.",
    images: ["/cars/car-1.jpeg"],
    color: "Silver",
  },
  {
    car: {
      make: "Honda",
      model: "Civic",
      year: "2019",
      serialPrice: 22000,
    },
    seller: {
      fullName: "Jane Smith",
      address: "Los Angeles, CA",
      contact: "555-987-6543",
    },
    sellingPrice: 20000,
    mileage: 25000,
    description: "Compact car with low mileage and clean interior.",
    images: ["/cars/car-2.jpeg"],
    color: "Blue",
  },
  {
    car: {
      make: "Ford",
      model: "Escape",
      year: "2021",
      serialPrice: 30000,
    },
    seller: {
      fullName: "Emily Brown",
      address: "Austin, TX",
      contact: "555-222-3333",
    },
    sellingPrice: 28000,
    mileage: 10000,
    description: "Spacious SUV with advanced safety features.",
    images: ["/cars/car-3.jpeg"],
    color: "White",
  },
  {
    car: {
      make: "Tesla",
      model: "Model 3",
      year: "2022",
      serialPrice: 45000,
    },
    seller: {
      fullName: "Robert Green",
      address: "San Francisco, CA",
      contact: "555-444-5555",
    },
    sellingPrice: 44000,
    mileage: 5000,
    description: "Electric car with autopilot and premium features.",
    images: ["/cars/car-4.jpeg"],
    color: "Black",
  },
  {
    car: {
      make: "Chevrolet",
      model: "Malibu",
      year: "2018",
      serialPrice: 21000,
    },
    seller: {
      fullName: "Anna White",
      address: "Miami, FL",
      contact: "555-666-7777",
    },
    sellingPrice: 19000,
    mileage: 30000,
    description: "Reliable sedan with a clean title and no accidents.",
    images: ["/cars/car-5.jpeg"],
    color: "Red",
  },
  {
    car: {
      make: "BMW",
      model: "X5",
      year: "2019",
      serialPrice: 55000,
    },
    seller: {
      fullName: "Michael Scott",
      address: "Scranton, PA",
      contact: "555-777-8888",
    },
    sellingPrice: 53000,
    mileage: 20000,
    description: "Luxury SUV with leather interior and all-wheel drive.",
    images: ["/cars/car-6.jpeg"],
    color: "Black",
  },
  {
    car: {
      make: "Nissan",
      model: "Altima",
      year: "2020",
      serialPrice: 24000,
    },
    seller: {
      fullName: "Karen Hill",
      address: "Denver, CO",
      contact: "555-888-9999",
    },
    sellingPrice: 22000,
    mileage: 18000,
    description: "Mid-size sedan with great fuel economy.",
    images: ["/cars/car-7.jpeg"],
    color: "Gray",
  },
  {
    car: {
      make: "Mercedes-Benz",
      model: "C-Class",
      year: "2021",
      serialPrice: 40000,
    },
    seller: {
      fullName: "Sandra Martinez",
      address: "Dallas, TX",
      contact: "555-000-1111",
    },
    sellingPrice: 39000,
    mileage: 12000,
    description: "Elegant sedan with advanced tech features.",
    images: ["/cars/car-8.jpeg"],
    color: "White",
  },
  {
    car: {
      make: "Hyundai",
      model: "Elantra",
      year: "2017",
      serialPrice: 18000,
    },
    seller: {
      fullName: "Paul Lee",
      address: "Seattle, WA",
      contact: "555-111-2222",
    },
    sellingPrice: 16000,
    mileage: 40000,
    description: "Affordable and reliable compact sedan.",
    images: ["/cars/car-9.jpeg"],
    color: "Blue",
  },
  {
    car: {
      make: "Kia",
      model: "Sorento",
      year: "2019",
      serialPrice: 32000,
    },
    seller: {
      fullName: "Betty Cooper",
      address: "Portland, OR",
      contact: "555-333-4444",
    },
    sellingPrice: 30000,
    mileage: 22000,
    description: "Family-friendly SUV with ample cargo space.",
    images: ["/cars/car-10.jpeg"],
    color: "Green",
  },
];
